name: eateryhub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.5.0
  equatable: ^2.0.7
  sqflite: ^2.3.1
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  test: ^1.25.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DMSans-Thin.ttf
          weight: 100
        
